### ISSUE TITLE
Is Cookie Logger?

### ISSUE THREAD

**Issue by GHCoderCass** [insaneinthamembrane/roblox-free-item-buyer#2]
Saw The Lines Of Code That Follow
cookie = pathlib.Path("cookie.txt").read_text()

session = requests.Session()
session.cookies.update({".ROBLOSECURITY": cookie})

**Comment by Oogaboogaman21** [comment]
and thats on the first line 💀

**Comment by TomerGamerTV** [comment]
bruh how tf do you think the program will buy items to your account? it needs your roblox cookie or login.

if you think its a logger search for code that connects to any website other than roblox.com

Clearly shows you have no experience with this kind of stuff

**Comment by Visionishere** [comment]
> bruh how tf do you think the program will buy items to your account? it needs your roblox cookie or login.
> 
> if you think its a logger search for code that connects to any website other than roblox.com
> 
> Clearly shows you have no experience with this kind of stuff

Agreed, no where in the code does it send the cookie to anyone. It technically is a cookie logger but not a malicious one since it doesn't GIVE anyone the cookie. now a days people see any github project logging a cookie and they freak out. programs like these NEED it.

**Comment by Oogaboogaman21** [comment]
> bruh how tf do you think the program will buy items to your account? it needs your roblox cookie or login.
> 
> if you think its a logger search for code that connects to any website other than roblox.com
> 
> Clearly shows you have no experience with this kind of stuff

You do not need the cookie to "buy every free item in Roblox" and long as you are already logged in, You do not need cookies to fucking automatically do those things. Every item has a url code and it's so simple to just implement a code without using cookies. Calling people inexperienced whilest you not even understanding anything.

**Comment by TomerGamerTV** [comment]
> > bruh how tf do you think the program will buy items to your account? it needs your roblox cookie or login.
> 
> > 
> 
> > if you think its a logger search for code that connects to any website other than roblox.com
> 
> > 
> 
> > Clearly shows you have no experience with this kind of stuff
> 
> 
> 
> You do not need the cookie to "buy every free item in Roblox" and long as you are already logged in, You do not need cookies to fucking automatically do those things. Every item has a url code and it's so simple to just implement a code without using cookies. Calling people inexperienced whilest you not even understanding anything. 
> 
> 
> 
> Not saying this shit is 100% a cookie logger but there is still no reason to require cookies in the code. Even worse to save it in a txt file.

Blud you clearly don't know how it works, are you saying that person should make a JavaScript script that will run inside the browser?

If a program needs to automate something in roblox it's needs the user's cookie to authenticate and automate actions and parsing though every single url will be slow af and unnecessary 

If you think it's so simple why don't you code it yourself?
You will still be using the user's cookies if you are going to automate stuff

I implemented the code to save the cookie inside a text file, it was made for convenience so people won't have to copy and paste the cookie every time into the console (also before my pull request the cookie wasn't even censored) I know this isn't a safe way of storing cookies but it's the user's responsibility to make sure it doesn't get leaked

**Comment by GHCoderCass** [comment]
### I Have Read Over This Issue Again 
**_With The Last Statement, I Have Withdrawn From It As I Did Not Look Into The Said Code Thoroughly And I Have Realized This Is A Legitimate Software That Does Work Utilizing The .ROBLOSECURITY Cookie To Purchase Free Avatar Items_**

**Comment by TomerGamerTV** [comment]
> ### I Have Read Over This Issue Again 
> 
> **_With The Last Statement, I Have Withdrawn From It As I Did Not Look Into The Said Code Thoroughly And I Have Realized This Is A Legitimate Software That Does Work Utilizing The .ROBLOSECURITY Cookie To Purchase Free Avatar Items_** 

A Roblox player admitting his mistake? Impressive I shall say gj 👏🏻
